const localStorageInitialData = [
  {
    category: 'Clothes',
    word: 't-shirt',
    translation: 'футболка',
    image: 'img/t-shirt.png',
    audioSrc: 'sounds/t-shirt.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Clothes',
    word: 'sweater',
    translation: 'свитер',
    image: 'img/sweater.png',
    audioSrc: 'sounds/sweater.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Clothes',
    word: 'jacket',
    translation: 'куртка',
    image: 'img/jacket.png',
    audioSrc: 'sounds/jacket.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Clothes',
    word: 'coat',
    translation: 'пальто',
    image: 'img/coat.png',
    audioSrc: 'sounds/coat.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Clothes',
    word: 'jeans',
    translation: 'джинсы',
    image: 'img/jeans.png',
    audioSrc: 'sounds/jeans.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Clothes',
    word: 'socks',
    translation: 'носки',
    image: 'img/socks.png',
    audioSrc: 'sounds/socks.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Clothes',
    word: 'shoes',
    translation: 'обувь',
    image: 'img/shoes.png',
    audioSrc: 'sounds/shoes.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Clothes',
    word: 'boots',
    translation: 'ботинки',
    image: 'img/boots.png',
    audioSrc: 'sounds/boots.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },

  {
    category: 'Family',
    word: 'mother',
    translation: 'мама',
    image: 'img/mother.png',
    audioSrc: 'sounds/mother.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Family',
    word: 'father',
    translation: 'папа',
    image: 'img/father.png',
    audioSrc: 'sounds/father.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Family',
    word: 'daughter',
    translation: 'дочь',
    image: 'img/daughter.png',
    audioSrc: 'sounds/daughter.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Family',
    word: 'son',
    translation: 'сын',
    image: 'img/son.png',
    audioSrc: 'sounds/son.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Family',
    word: 'grandmother',
    translation: 'бабушка',
    image: 'img/grandmother.png',
    audioSrc: 'sounds/grandmother.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Family',
    word: 'grandfather',
    translation: 'дедушка',
    image: 'img/grandfather.png',
    audioSrc: 'sounds/grandfather.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Family',
    word: 'aunt',
    translation: 'тётя',
    image: 'img/aunt.png',
    audioSrc: 'sounds/aunt.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Family',
    word: 'uncle',
    translation: 'дядя',
    image: 'img/uncle.png',
    audioSrc: 'sounds/uncle.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },

  {
    category: 'Animals',
    word: 'dog',
    translation: 'собака',
    image: 'img/dog.png',
    audioSrc: 'sounds/dog.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Animals',
    word: 'cat',
    translation: 'кот',
    image: 'img/cat.png',
    audioSrc: 'sounds/cat.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Animals',
    word: 'cow',
    translation: 'корова',
    image: 'img/cow.png',
    audioSrc: 'sounds/cow.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Animals',
    word: 'duck',
    translation: 'утка',
    image: 'img/duck.png',
    audioSrc: 'sounds/duck.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Animals',
    word: 'hen',
    translation: 'курица',
    image: 'img/hen.png',
    audioSrc: 'sounds/hen.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Animals',
    word: 'pig',
    translation: 'свинья',
    image: 'img/pig.png',
    audioSrc: 'sounds/pig.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Animals',
    word: 'rabbit',
    translation: 'кролик',
    image: 'img/rabbit.png',
    audioSrc: 'sounds/rabbit.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Animals',
    word: 'sheep',
    translation: 'овца',
    image: 'img/sheep.png',
    audioSrc: 'sounds/sheep.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },

  {
    category: 'Jobs',
    word: 'artist',
    translation: 'художник',
    image: 'img/artist.png',
    audioSrc: 'sounds/artist.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Jobs',
    word: 'chef',
    translation: 'повар',
    image: 'img/chef.png',
    audioSrc: 'sounds/chef.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Jobs',
    word: 'engineer',
    translation: 'инженер',
    image: 'img/construction_worker.png',
    audioSrc: 'sounds/engineer.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Jobs',
    word: 'doctor',
    translation: 'врач',
    image: 'img/doctor.png',
    audioSrc: 'sounds/doctor.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Jobs',
    word: 'firefighter',
    translation: 'пожарный',
    image: 'img/firefighter.png',
    audioSrc: 'sounds/firefighter.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Jobs',
    word: 'policeman',
    translation: 'полицейский',
    image: 'img/policeman.png',
    audioSrc: 'sounds/policeman.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Jobs',
    word: 'teacher',
    translation: 'учитель',
    image: 'img/teacher.png',
    audioSrc: 'sounds/teacher.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Jobs',
    word: 'veterinarian',
    translation: 'ветеринар',
    image: 'img/veterinarian.png',
    audioSrc: 'sounds/veterinarian.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },

  {
    category: 'Music',
    word: 'clarinet',
    translation: 'кларнет',
    image: 'img/clarinet.png',
    audioSrc: 'sounds/clarinet.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Music',
    word: 'cymbal',
    translation: 'тарелка',
    image: 'img/cymbal.png',
    audioSrc: 'sounds/cymbal.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Music',
    word: 'drums',
    translation: 'барабаны',
    image: 'img/drums.png',
    audioSrc: 'sounds/drums.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Music',
    word: 'flute',
    translation: 'флейта',
    image: 'img/flute.svg',
    audioSrc: 'sounds/flute.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Music',
    word: 'guitar',
    translation: 'гитара',
    image: 'img/guitar.png',
    audioSrc: 'sounds/guitar.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Music',
    word: 'trumpet',
    translation: 'труба',
    image: 'img/trumpet.png',
    audioSrc: 'sounds/trumpet.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Music',
    word: 'piano',
    translation: 'пианино',
    image: 'img/piano.png',
    audioSrc: 'sounds/piano.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Music',
    word: 'violin',
    translation: 'скрипка',
    image: 'img/violin.png',
    audioSrc: 'sounds/violin.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },

  {
    category: 'Shapes',
    word: 'circle',
    translation: 'круг',
    image: 'img/circle.png',
    audioSrc: 'sounds/circle.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Shapes',
    word: 'diamond',
    translation: 'бриллиант',
    image: 'img/diamond.png',
    audioSrc: 'sounds/diamond.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Shapes',
    word: 'heart',
    translation: 'сердце',
    image: 'img/heart.png',
    audioSrc: 'sounds/heart.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Shapes',
    word: 'octagon',
    translation: 'восьмиугольник',
    image: 'img/octagon.png',
    audioSrc: 'sounds/octagon.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Shapes',
    word: 'rectangle',
    translation: 'прямоугольник',
    image: 'img/rectangle.png',
    audioSrc: 'sounds/rectangle.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Shapes',
    word: 'square',
    translation: 'квадрат',
    image: 'img/square.png',
    audioSrc: 'sounds/square.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Shapes',
    word: 'star',
    translation: 'звезда',
    image: 'img/star.png',
    audioSrc: 'sounds/star.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Shapes',
    word: 'triangle',
    translation: 'треугольник',
    image: 'img/triangle.png',
    audioSrc: 'sounds/triangle.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },

  {
    category: 'Tools',
    word: 'bolt',
    translation: 'болт',
    image: 'img/bolt.png',
    audioSrc: 'sounds/bolt.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Tools',
    word: 'hammer',
    translation: 'молоток',
    image: 'img/hammer.png',
    audioSrc: 'sounds/hammer.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Tools',
    word: 'nut',
    translation: 'гайка',
    image: 'img/nut.png',
    audioSrc: 'sounds/nut.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Tools',
    word: 'pliers',
    translation: 'плоскогубцы',
    image: 'img/pliers.png',
    audioSrc: 'sounds/pliers.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Tools',
    word: 'saw',
    translation: 'пила',
    image: 'img/saw.png',
    audioSrc: 'sounds/saw.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Tools',
    word: 'screwdriver',
    translation: 'отвёртка',
    image: 'img/screwdriver.png',
    audioSrc: 'sounds/screwdriver.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Tools',
    word: 'shovel',
    translation: 'лопата',
    image: 'img/shovel.png',
    audioSrc: 'sounds/shovel.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Tools',
    word: 'wrench',
    translation: 'гаечный ключ',
    image: 'img/wrench.png',
    audioSrc: 'sounds/wrench.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },

  {
    category: 'Toys',
    word: 'aeroplane',
    translation: 'самолёт',
    image: 'img/aeroplane.png',
    audioSrc: 'sounds/aeroplane.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Toys',
    word: 'ball',
    translation: 'мяч',
    image: 'img/ball.png',
    audioSrc: 'sounds/ball.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Toys',
    word: 'bicycle',
    translation: 'велосипед',
    image: 'img/bicycle.png',
    audioSrc: 'sounds/bicycle.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Toys',
    word: 'car',
    translation: 'машина',
    image: 'img/car.png',
    audioSrc: 'sounds/car.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Toys',
    word: 'crayons',
    translation: 'мелки',
    image: 'img/crayons.png',
    audioSrc: 'sounds/crayons.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Toys',
    word: 'doll',
    translation: 'кукла',
    image: 'img/doll.png',
    audioSrc: 'sounds/doll.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Toys',
    word: 'teddy bear',
    translation: 'плюшевый мишка',
    image: 'img/teddy_bear.png',
    audioSrc: 'sounds/teddy_bear.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
  {
    category: 'Toys',
    word: 'train',
    translation: 'поезд',
    image: 'img/train.png',
    audioSrc: 'sounds/train.mp3',
    clicks: 0,
    right: 0,
    wrong: 0,
    percent: 0,
  },
];

export default localStorageInitialData;
